#!/bin/bash

# env 파일 불러오기
export $(egrep -v '^#' .env | xargs)

# 프린트해보기
echo "AWS_PROFILE=$AWS_PROFILE"
echo "AWS_REGION=$AWS_REGION"
echo "CONTENTS_BUCKET=$CONTENTS_BUCKET"
echo "CONTENTS_CONSUMER_LAMBDA_NAME=$CONTENTS_CONSUMER_LAMBDA_NAME"
echo "CONTENTS_CONSUMER_LAMBDA_KEY=$CONTENTS_CONSUMER_LAMBDA_KEY"
echo "CONTENTS_CONSUMER_LAMBDA_BUCKET=$CONTENTS_CONSUMER_LAMBDA_BUCKET"
echo "CONTENTS_CONSUMER_LAMBDA_ZIP_FILE_NAME=$CONTENTS_CONSUMER_LAMBDA_ZIP_FILE_NAME"
echo "CONTENTS_STAND_BY_QUEUE=$CONTENTS_STAND_BY_QUEUE"
echo "CONTENTS_STAND_BY_QUEUE_URL=$CONTENTS_STAND_BY_QUEUE_URL"

echo "end"
